### ISSUE TITLE
Perubahan nama kolom 

### ISSUE THREAD

**Issue by guaychou** [guaychou/KuyJalan#12]
perubahan nama kolom di kota,tempat wisata (nama => nama_kategoris dst) , membuat tidak dapat menampilkan kota / kategori pada menu dropdown yang ada .

**Comment by araditama** [comment]
Yang diubah nama kolom di database atau gimana?

**Comment by guaychou** [comment]
ya kubuat di  laravel nya mas , kan di migrate terus refresh
